### ISSUE TITLE
error message not returned when vi-mongo executable doesnt exist in PATH

### ISSUE THREAD

**Issue by noornee** [kopecmaciej/vi-mongo.nvim#1]
Hello, i discovered this plugin through the neovim subreddit and i must say, your website looks soo awesome!

## issue

while testing the plugin, i noticed that the terminal window opens briefly and then closes (this is because i didnt have the `vi-mongo` executable installed)

i took a peek at the code and tried debugging why it wasnt returning the error message and i found out that the [job_id](https://github.com/kopecmaciej/vi-mongo.nvim/blob/6f0fd7b801c579a52aed509b42d53356a8446bcd/lua/vi-mongo/window.lua#L44) never returned `0`

a way this could be resolved is by checking for the existence on the `vi-mongo` executable before running every other thing.

i would love to open a pr to resolve this if thats okay with you ^^

p.s. im not very familiar with lua or the neovim API, but this change seems relatively simple for me to implement.

**Comment by kopecmaciej** [comment]
Hey, thanks for your kind words and also for finding this bug, I totally miss that someone can only install the plugin and do not have `vi-mongo` yet installed. Feel free to open PR. Thanks!
